# Generated by Django 4.2.3 on 2023-07-08 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("perfil", "0002_conta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoria",
            old_name="Categoria",
            new_name="categoria",
        ),
        migrations.RenameField(
            model_name="conta",
            old_name="Valor",
            new_name="valor",
        ),
    ]
